This is a testharness.js-based test.
[FAIL] clean close should be clean
  promise_test: Unhandled rejection with value: object "WebSocketError: WebSocket closed before handshake complete."
[FAIL] close frame with no body should result in status code 1005
  promise_test: Unhandled rejection with value: object "WebSocketError: WebSocket was not cleanly closed."
[FAIL] reason should be passed through
  promise_test: Unhandled rejection with value: object "WebSocketError: WebSocket was not cleanly closed."
[FAIL] UTF-8 reason should work
  promise_test: Unhandled rejection with value: object "WebSocketError: WebSocket was not cleanly closed."
[FAIL] close with unwritten data should not be considered clean
  promise_test: Unhandled rejection with value: object "WebSocketError: WebSocket closed before handshake complete."
[FAIL] remote code and reason should be used
  promise_test: Unhandled rejection with value: object "WebSocketError: WebSocket closed before handshake complete."
[FAIL] abrupt close should give an error
  promise_test: Unhandled rejection with value: object "WebSocketError: WebSocket closed before handshake complete."
Harness: the test ran to completion.

